const test=require('node:test'),assert=require('node:assert/strict'),A=require('../arena/core.js');
function grid(){const elements=[];for(let y=0;y<15;y++)for(let x=0;x<15;x++)elements.push({type:'node',id:y*15+x,lat:-y*.00045,lon:x*.00045});let way=1000;for(let y=0;y<15;y++)elements.push({type:'way',id:way++,nodes:Array.from({length:15},(_,x)=>y*15+x)});for(let x=0;x<15;x++)elements.push({type:'way',id:way++,nodes:Array.from({length:15},(_,y)=>y*15+x)});return A.makeGraph({location:{lat:0,lng:0},roads:{elements},roadsSha256:'test-grid'});}
const course={starts:[0,14,210,224],goals:[7,217,112,104,120]};
function fixture(){const graph=grid(),m=A.create(graph,{course,bots:false});m.start();return {graph,m};}
function command(m,player,type,fields={}){m.command({player,type,seq:m.state.players[player].lastSeq+1,...fields});m.step();}
test('four distinct starts, five shared goals and deterministic road traversal',()=>{const {m}=fixture();assert.equal(m.state.players.length,4);assert.equal(new Set(m.state.players.map(p=>p.node)).size,4);command(m,0,'plan',{node:7});for(let i=0;i<80;i++)m.step();assert.equal(m.state.players[0].goal,1);assert.equal(m.state.players[0].credits,5);assert.equal(m.state.players[0].score,1000);});
test('duplicate commands cannot mint charge; range and ownership are validated',()=>{const {m}=fixture(),id=m.state.pickups.find(i=>i.node===0).id;const c={player:0,seq:1,type:'collect',item:id};m.command(c);m.command(c);m.step();assert.equal(m.state.players[0].credits,5);command(m,1,'collect',{item:id});assert.equal(m.state.players[1].credits,3);});
test('endpoint barriers and trapping cuts are rejected without charging',()=>{const {m}=fixture();command(m,0,'barrier',{node:7});assert.equal(m.state.barriers.length,0);assert.equal(m.state.players[0].credits,3);command(m,0,'cut',{victim:1});assert.equal(m.state.players[0].credits,3);});
test('safe barriers block edges, preserve all remaining objectives and expire',()=>{const graph=grid(),m=A.create(graph,{course:{starts:[15,16,17,18],goals:[0,1,2,3,4]},bots:false});m.start();const safe=graph.component.find(id=>m.validBarrier(graph.nodes.get(id)));assert.notEqual(safe,undefined);command(m,0,'barrier',{node:safe});assert.equal(m.state.barriers.length,1);assert.equal(m.state.players[0].credits,0);for(const p of m.state.players)assert.ok(m.route(p.node,m.state.goals[p.goal]));for(let i=0;i<201;i++)m.step();assert.equal(m.state.barriers.length,0);});
test('cut makes a real repair task; repair clears it and grants repeat-hit protection',()=>{const {m}=fixture();m.state.players[0].credits=10;command(m,1,'plan',{node:7});for(let i=0;i<80;i++)m.step();command(m,1,'plan',{node:97});for(let i=0;i<60;i++)m.step();const before=m.state.players[1].node;command(m,0,'cut',{victim:1});const p=m.state.players[1];assert.ok(p.repair);assert.notEqual(p.node,before);assert.equal(p.repair.to,before);command(m,1,'plan',{node:p.repair.to});for(let i=0;i<80;i++)m.step();assert.equal(p.repair,null);assert.ok(p.protectedUntil>m.state.time);command(m,0,'cut',{victim:1});assert.equal(p.repair,null);});
test('shortcut is meter-bounded, spends currency and moves continuously',()=>{const {m}=fixture();m.state.players[0].credits=10;command(m,0,'shortcut',{node:224});assert.equal(m.state.players[0].credits,10);command(m,0,'shortcut',{node:32});assert.equal(m.state.players[0].credits,5);assert.equal(m.state.players[0].node,0);for(let i=0;i<30;i++)m.step();assert.equal(m.state.players[0].node,32);});
test('pause freezes authority, snapshots restore deterministic continuation',()=>{const {m,graph}=fixture();command(m,0,'plan',{node:7});m.pause();const t=m.state.time;m.step();assert.equal(m.state.time,t);m.resume();const clone=A.create(graph,{course,bots:false});clone.restore(m.snapshot());for(let i=0;i<100;i++){m.step();clone.step();}assert.deepEqual(m.snapshot(),clone.snapshot());});
test('bots finish the course and match ends with a coherent winner',()=>{const graph=grid(),m=A.create(graph,{course,bots:true});m.start();for(let i=0;i<10000&&m.state.status!=='finished';i++)m.step();assert.equal(m.state.status,'finished');assert.ok(m.state.players[m.state.winner].goal===5);assert.notEqual(m.state.winner,0);});
test('real New Cairo is a substantial connected graph with a playable five-destination course',()=>{const pack=require('../data/cities/fallback/new-cairo.json'),graph=A.makeGraph(pack),course=A.makeCourse(graph);assert.ok(graph.component.length>30000);assert.equal(new Set(course.starts).size,4);assert.equal(new Set(course.goals).size,5);for(const start of course.starts)assert.ok(A.route(graph,start,course.goals[0]));});
test('a human command stream can complete all five real Cairo destinations against the bots',()=>{
 const graph=A.makeGraph(require('../data/cities/fallback/new-cairo.json')),m=A.create(graph);m.start();
 for(let t=0;t<10000&&m.state.status!=='finished';t++){
  const p=m.state.players[0];if(p.finishedAt===null&&!p.queue.length){const r=m.route(p.node,m.target(p));assert.ok(r);let meters=0,last=p.node;for(let i=1;i<r.path.length;i++){meters+=A.distance(graph.nodes.get(r.path[i-1]),graph.nodes.get(r.path[i]));if(meters>900)break;last=r.path[i];}assert.notEqual(last,p.node);m.command({player:0,seq:p.lastSeq+1,type:'plan',node:last});}
  m.step();
 }
 assert.equal(m.state.status,'finished');assert.equal(m.state.players[0].goal,5);assert.equal(m.state.winner,0);assert.ok(m.state.players[0].score<=5000);
});
