const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function setup(){let time=0;const window={};vm.runInNewContext(fs.readFileSync('engine/round-metrics.js','utf8'),{window,performance:{now:()=>time},document:{getElementById:()=>null}});return {m:window.PathfindrRoundMetrics,t:n=>time=n};}
test('high-DPI framebuffer does not repeatedly resize and clear presentation overlays',()=>{
 const game=fs.readFileSync('game.js','utf8'),start=game.indexOf('function ensureMapPresentationSync()'),end=game.indexOf('\nfunction ',start+10);let resizes=0;
 const canvas={width:390,height:844};const context={GameState:{map:{isMoving:()=>false},drawCanvas:canvas,vizCanvas:canvas,previewCanvas:canvas,presentationSyncKey:'same'},WebGLRenderer:{canvas:{width:780,height:1688},cssWidth:390,cssHeight:844},getMapContainerSize:()=>({width:390,height:844}),getMapPresentationStateKey:()=> 'same',resizeCanvases:()=>resizes++};
 vm.runInNewContext(game.slice(start,end)+';ensureMapPresentationSync();ensureMapPresentationSync();',context);assert.equal(resizes,0);
});
test('round timer excludes preload, reveal and recap; claims remain possible during reveal',()=>{const {m,t}=setup();t(4000);m.begin('one');t(9000);assert.equal(m.snapshot().elapsedMs,0);m.start();t(19000);m.stop();t(39000);m.claim({key:'a',type:'library'});assert.equal(m.snapshot().elapsedMs,10000);assert.equal(m.snapshot().collectionPoints,40);m.begin('two');assert.equal(m.snapshot().elapsedMs,0);assert.equal(m.snapshot().collectionPoints,0);});
test('collection points deduplicate and daily score is bounded separately from Classic',()=>{const {m}=setup();assert.equal(m.points([{key:'a',type:'burger'},{key:'a',type:'burger'},{key:'x',type:'unknown'}]),25);assert.equal(m.score(100,10000,60000).total,1250);assert.equal(m.score(90,40,60000).total,990);assert.equal(m.score(100,200,0).speed,0);assert.equal(m.score(100,200,1000,true).total,0);});
test('zoom optics preserve a readable core while shrinking halo more aggressively',()=>{const window={};vm.runInNewContext(fs.readFileSync('engine/visual-fidelity.js','utf8'),{window});const a=window.PathfindrFidelity.atZoom(11),b=window.PathfindrFidelity.atZoom(16);assert.ok(a.halo<a.core);assert.ok(a.bloom<b.bloom);assert.equal(b.halo,1);});
test('route completion stops timer before lock-in; Classic formula is unchanged',()=>{const game=fs.readFileSync('game.js','utf8');const submit=game.slice(game.indexOf('async function submitRoute()'),game.indexOf('// Hero animation:'));assert.ok(submit.indexOf('PathfindrRoundMetrics?.stop()')<submit.indexOf('await playUserPathLockInAnimation()'));assert.ok(game.includes('Math.round((efficiency / 100) * CONFIG.maxScore)'));});
