const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function setup(){const c={console,TextEncoder,TextDecoder,Response,Blob,CompressionStream,DecompressionStream,btoa,atob,crypto:require('node:crypto').webcrypto};c.window=c;vm.createContext(c);for(const file of ['share-data.js','route-archive.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../engine',file),'utf8'),c);return c;}
function fixture(){return {v:1,kind:'result',title:'Miami test run',maps:[{location:{name:'Miami',lng:-80.19,lat:25.77},nodes:[[-80.19,25.77],[-80.189,25.77],[-80.188,25.77]],edges:[[0,1],[1,2]]}],rounds:[{map:0,start:[-80.19,25.77],end:[-80.188,25.77],difficulty:'medium',score:920,userDistance:.3,optimalDistance:.276,userPath:[[-80.19,25.77],[-80.188,25.77]],optimalPath:[[-80.19,25.77],[-80.188,25.77]],pickups:[{key:'landmark:a',name:'Freedom Tower',type:'landmark',pos:[-80.19,25.77]}],collected:[{key:'landmark:a',name:'Freedom Tower',type:'landmark',pos:[-80.19,25.77],collectedAt:1234}]}]};}
test('portable result round-trip retains geography, score and collectible identity',async()=>{const c=setup(),d=c.PathfindrShareData,p=fixture(),decoded=await d.decode(await d.encode(p));assert.equal(decoded.rounds[0].score,920);assert.equal(decoded.rounds[0].collected[0].collectedAt,1234);assert.deepEqual(JSON.parse(JSON.stringify(decoded.rounds[0].userPath)),p.rounds[0].userPath);});
test('challenge export removes solutions, scores and collected timestamps',()=>{const d=setup().PathfindrShareData,p=d.challenge(fixture());assert.equal(p.kind,'challenge');assert.equal(p.rounds[0].userPath,undefined);assert.equal(p.rounds[0].score,undefined);assert.equal(p.rounds[0].collected,undefined);assert.equal(p.rounds[0].pickups.length,1);});
test('library identities survive share export and import',async()=>{const d=setup().PathfindrShareData,p=fixture();p.rounds[0].pickups[0].type='library';p.rounds[0].collected[0].type='library';const result=await d.decode(await d.encode(p));assert.equal(result.rounds[0].pickups[0].type,'library');assert.equal(result.rounds[0].collected[0].type,'library');});
test('reject unsupported versions, invalid coordinates and oversized input',async()=>{const d=setup().PathfindrShareData,p=fixture();p.v=99;assert.throws(()=>d.validate(p));p.v=1;p.rounds[0].start=[Infinity,25];assert.throws(()=>d.validate(p));await assert.rejects(d.decode('PF1.'+'a'.repeat(d.MAX_CODE)));await assert.rejects(d.decode('javascript:alert(1)'));});
test('reject decompression bomb before parsing',async()=>{const d=setup().PathfindrShareData,raw=new TextEncoder().encode(' '.repeat(4_000_001)),bytes=new Uint8Array(await new Response(new Blob([raw]).stream().pipeThrough(new CompressionStream('gzip'))).arrayBuffer());const code='PF1z.'+Buffer.from(bytes).toString('base64url');await assert.rejects(d.decode(code),/size limit/);});
test('snapshot endpoints must match and be connected; changed packs cannot substitute',()=>{const d=setup().PathfindrShareData,p=fixture();const r=d.resolve(p.maps[0],p.rounds[0]);assert.equal(r.start,1);assert.equal(r.end,3);p.maps[0].edges=[];assert.throws(()=>d.resolve(p.maps[0],p.rounds[0]),/not connected/);assert.throws(()=>d.resolve({packId:'miami',version:'old'},p.rounds[0]),/version/);});
test('archive keeps prior rounds, updates post-result pickups, and starts a fresh run',async()=>{const c=setup(),a=c.PathfindrArchive,p=fixture(),roads=c.PathfindrShareData.resolve(p.maps[0],p.rounds[0]).data;a.graph(roads,p.maps[0].location);a.begin(1);a.capture(p.rounds[0]);const first=a.current().id;a.begin(2);a.capture({...p.rounds[0],score:700});a.discoveries([]);assert.equal(a.selected().rounds.length,2);assert.equal(a.selected(0).rounds[0].score,920);assert.equal(a.selected(1).rounds[0].collected.length,0);a.begin(1);assert.notEqual(a.current().id,first);assert.equal((await a.list()).length,1);assert.match(a.state().error,/Storage unavailable/);});
