"""Build-time soundtrack envelopes/onsets. Requires ffmpeg and numpy; no service calls.
Positive log-spectral flux follows AudioLabs FMP C6S1_NoveltySpectral.
"""
import json, pathlib, subprocess, hashlib
import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[1]
SR, N, HOP = 22050, 2048, 512
tracks = {}
for source in sorted((ROOT / 'Music').glob('*.mp3')):
    pcm = subprocess.run(['ffmpeg', '-v', 'error', '-i', str(source), '-f', 'f32le', '-ac', '1', '-ar', str(SR), 'pipe:1'], check=True, capture_output=True).stdout
    samples = np.frombuffer(pcm, dtype='<f4')
    frames = np.lib.stride_tricks.sliding_window_view(samples, N)[::HOP]
    magnitude = np.abs(np.fft.rfft(frames * np.hanning(N), axis=1))
    logspec = np.log1p(magnitude * 10)
    flux = np.maximum(0, np.diff(logspec, axis=0, prepend=logspec[:1])).mean(axis=1)
    local = np.convolve(flux, np.ones(43)/43, mode='same')
    frequencies = np.fft.rfftfreq(N, 1/SR)
    bands = np.stack([np.sqrt(np.mean(magnitude[:, (frequencies >= lo) & (frequencies < hi)]**2, axis=1)) for lo, hi in [(40,250),(250,2200),(2200,9000)]], axis=1)
    scale = np.maximum(np.percentile(bands, 95, axis=0), 1e-6)
    bands = np.clip(bands / scale, 0, 1)
    threshold = max(float(np.percentile(flux, 65)), .002)
    events, last = [], -1
    for i in range(1, len(flux)-1):
        t = (i*HOP+N/2)/SR
        if t-last < .38 or flux[i] < max(threshold, local[i]*1.35) or not (flux[i] >= flux[i-1] and flux[i] > flux[i+1]):
            continue
        strength = min(1., float(flux[i]/max(threshold*3, .001)))
        kind = int(np.argmax(bands[i] * [1.1, 1, .85]))
        events.append([round(t,3), round(strength,3), kind]); last=t
    tracks[source.name] = {'sha256': hashlib.sha256(source.read_bytes()).hexdigest(), 'step': HOP*2/SR, 'offset': N/2/SR, 'duration': len(samples)/SR, 'bands': np.round(bands[::2]*255).astype(int).tolist(), 'events': events}
    print(source.name, len(events), 'onsets')
out = ROOT / 'data' / 'soundtrack-analysis.js'
out.write_text('/* Generated by scripts/analyze-soundtrack.py. */\nwindow.PathfindrSoundtrackAnalysis='+json.dumps({'version':1,'tracks':tracks},separators=(',',':'))+';\n')
print(out, out.stat().st_size, 'bytes')
